### ISSUE TITLE
remote_dataset.export returns exception when sending annotation_class_ids

### ISSUE THREAD

**Issue by renzodgc** [v7labs/darwin-py#395] opened 2022-04-08 15:18 UTC
### Current behavior
When running `dataset.export(name=release_name, annotation_class_ids=annotation_classes, include_url_token=True)`, where `annotation_classes` is a list of strings with the name of the class `["ClassName"]`

I get:
`*** requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://darwin.v7labs.com/api/datasets/{dataset_id}/exports`

I can see on darwin.v7labs.com that the release was created and is "generating" but it never finishes (I've been running one since yesterday)

I also just tried generating a release manually through the website selecting a class and in that case the same behavior happens, so presumably, this is an issue with darwin's API and not with `darwin-py` (I didn't see a repository in which to report it)

### Expected behavior
It should create a release with only the selected classes.

---

I also tried passing the numerical string I get from `dataset.fetch_remote_classes()[0]['id']` both in integer format and string format.

In both cases, it threw no exception but the release was created with all the classes associated to the dataset (rather than the one provided)

**Comment by Fl4m3Ph03n1x** [comment] 2022-04-13 10:31
Hello @renzodgc , we are aware of this issue and are working to fix it. 
Once I believe the issue is fixed on our side, I will update this ticket.

In the meantime, I appreciate your patience and I thank you for taking the time to report it. 
Best regards, 
V7 Wind Team.

**Comment by Fl4m3Ph03n1x** [comment] 2022-04-21 12:47
Hello @renzodgc we believe to have fixed the issue now, as it works correctly in our PROD site. 
I will now close this ticket, however, if you still experience the same issue feel free to re-open it.

Thank your for your patience and for the report, 
Best regards,
V7 Wind Team

**Closed by Fl4m3Ph03n1x** 2022-04-21 12:47 UTC
Labels: bug, wind-team

**Comment by renzodgc** [comment] 2022-04-26 19:25
Hi, I uploaded the library to its latest version (glad to see include_autorship is now released :raised_hands:) but I still get the same issue with the parameter `annotation_class_ids` when passing a list with the name of the annotation I am interested (like `["Tooth"]` for instance.

I am able to filter classes when exporting releases through the web, although the jobs I created on darwin-py still appear as "Generating" with a loading circle that doesn't end.
