### ISSUE TITLE
Response is not JSON encoded

### ISSUE THREAD

**Issue by YousefRabi** [v7labs/darwin-py#207] opened 2021-09-22 01:05 UTC
Getting this error when importing annotations to a video dataset in "New" status.

warning, failed to upload annotation to 209824341 {'error': 'Response is not JSON encoded', 'status_code': 500, 'text': 'Something went wrong'}

What could be the issue?

**Comment by andreaazzini** [comment] 2021-09-22 07:57
Hi @YousefRabi, we are looking into it ASAP, and will keep you posted!
Cheers

**Comment by andreaazzini** [comment] 2021-09-22 16:26
Hi @YousefRabi, we found the root cause of your issue, which is not related to darwin-py, but rather the backend service of Darwin. I have forwarded your issue to the right team, and linked it your support ticket. We will follow up there, and I'll close this issue here in this repo for the time being.

Thanks!

**Closed by andreaazzini** 2021-09-22 16:26 UTC

**Comment by YousefRabi** [comment] 2021-09-22 20:10
Thanks @andreaazzini for getting up on top of this.
