### ISSUE TITLE
pkg_resources.UnknownExtra: mpire 2.6.0 has no such extra feature 'dev'

### ISSUE THREAD

**Issue by biendltb** [v7labs/darwin-py#550] opened 2023-03-01 10:59 UTC
Hi team,

When I tried to build a python package that uses darwin-py as one of its dependencies, it's an error in the recent release with `mpire` package. 

Full trace:

```bash
$ python setup.py build
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/test_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2760, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'dev'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    setup(
  File "/home/ubuntu/anaconda3/envs/test_env/lib/python3.8/site-packages/setuptools/__init__.py", line 86, in setup
    _install_setup_requires(attrs)
  File "/home/ubuntu/anaconda3/envs/test_env/lib/python3.8/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/ubuntu/anaconda3/envs/test_env/lib/python3.8/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/home/ubuntu/anaconda3/envs/test_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 803, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/ubuntu/anaconda3/envs/test_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2762, in requires
    raise UnknownExtra(
pkg_resources.UnknownExtra: mpire 2.6.0 has no such extra feature 'dev'
```

Do you know how should I avoid this error from mpire?

Thank you!

**Comment by filippocastelli** [comment] 2023-03-02 11:04
confirm this bug:
When building a package (`setup.py `style, not poetry) that has
`darwin-py` in its requirements I get the same `UnknownExtras` problems.
The issue 

```bash
(darwin) phil@gondolin:~/repos/model_creation_utils/####2darwin$ ####2darwin -h
Traceback (most recent call last):
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2760, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'dev'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/phil/anaconda3/envs/darwin/bin/####2darwin", line 33, in <module>
    sys.exit(load_entry_point('####2darwin', 'console_scripts', '####2darwin')())
  File "/home/phil/anaconda3/envs/darwin/bin/####2darwin", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/phil/repos/model_creation_utils/####2darwin/####2darwin/__init__.py", line 1, in <module>
    from ####2darwin.darwin_to_#### import DarwinTo####
  File "/home/phil/repos/model_creation_utils/####2darwin/####2darwin/darwin_to_####.py", line 8, in <module>
    from darwin.utils import parse_darwin_json
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/__init__.py", line 1, in <module>
    import darwin.dataset  # noqa
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/dataset/__init__.py", line 1, in <module>
    from darwin.dataset.local_dataset import LocalDataset  # noqa
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/dataset/local_dataset.py", line 9, in <module>
    from darwin.dataset.utils import get_classes, get_release_path, load_pil_image
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/dataset/utils.py", line 16, in <module>
    from darwin.importer.formats.darwin import parse_path
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/importer/__init__.py", line 5, in <module>
    from .importer import import_annotations  # noqa
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/importer/importer.py", line 26, in <module>
    from mpire import WorkerPool, tqdm
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/mpire/__init__.py", line 4, in <module>
    from mpire.pool import WorkerPool
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/mpire/pool.py", line 21, in <module>
    from mpire.dashboard.connection_utils import get_dashboard_connection_details
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/mpire/dashboard/__init__.py", line 2, in <module>
    from mpire.dashboard.dashboard import connect_to_dashboard, start_dashboard
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/mpire/dashboard/dashboard.py", line 8, in <module>
    from pkg_resources import resource_string
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 803, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2762, in requires
    raise UnknownExtra(
pkg_resources.UnknownExtra: types-requests 2.28.11.15 has no such extra feature 'dev'
(darwin) phil@gondolin:~/repos/model_creation_utils/####2darwin$ 
```

The issue is not solved by installing `darwin-py`  with test extras by including `darwin-py[test]`, in fact  we just have the same problem on a different package (`responses`)

```bash
(darwin) phil@gondolin:~/repos/model_creation_utils/####2darwin$ ####2darwin -h
Traceback (most recent call last):
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2760, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'test'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/phil/anaconda3/envs/darwin/bin/####2darwin", line 33, in <module>
    sys.exit(load_entry_point('####2darwin', 'console_scripts', '####2darwin')())
  File "/home/phil/anaconda3/envs/darwin/bin/####2darwin", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/phil/repos/model_creation_utils/####2darwin/####2darwin/__init__.py", line 1, in <module>
    from ####2darwin.darwin_to_#### import DarwinTo####
  File "/home/phil/repos/model_creation_utils/####2darwin/####2darwin/darwin_to_####.py", line 8, in <module>
    from darwin.utils import parse_darwin_json
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/__init__.py", line 1, in <module>
    import darwin.dataset  # noqa
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/dataset/__init__.py", line 1, in <module>
    from darwin.dataset.local_dataset import LocalDataset  # noqa
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/dataset/local_dataset.py", line 9, in <module>
    from darwin.dataset.utils import get_classes, get_release_path, load_pil_image
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/dataset/utils.py", line 16, in <module>
    from darwin.importer.formats.darwin import parse_path
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/importer/__init__.py", line 5, in <module>
    from .importer import import_annotations  # noqa
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/importer/importer.py", line 26, in <module>
    from mpire import WorkerPool, tqdm
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/mpire/__init__.py", line 4, in <module>
    from mpire.pool import WorkerPool
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/mpire/pool.py", line 21, in <module>
    from mpire.dashboard.connection_utils import get_dashboard_connection_details
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/mpire/dashboard/__init__.py", line 2, in <module>
    from mpire.dashboard.dashboard import connect_to_dashboard, start_dashboard
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/mpire/dashboard/dashboard.py", line 8, in <module>
    from pkg_resources import resource_string
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 803, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2762, in requires
    raise UnknownExtra(
pkg_resources.UnknownExtra: responses 0.22.0 has no such extra feature 'test'
```

Pre-installing `darwin-py` doesn't seem to be a solution either, the problem just shifts to `types-requests`.

```bash
(darwin) phil@gondolin:~/repos/model_creation_utils/####2darwin$ ####2darwin
Traceback (most recent call last):
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2760, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'dev'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/phil/anaconda3/envs/darwin/bin/####2darwin", line 33, in <module>
    sys.exit(load_entry_point('####2darwin', 'console_scripts', '####2darwin')())
  File "/home/phil/anaconda3/envs/darwin/bin/####2darwin", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/phil/repos/model_creation_utils/####2darwin/####2darwin/__init__.py", line 1, in <module>
    from ####2darwin.darwin_to_#### import DarwinTo####
  File "/home/phil/repos/model_creation_utils/####2darwin/####2darwin/darwin_to_####.py", line 8, in <module>
    from darwin.utils import parse_darwin_json
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/__init__.py", line 1, in <module>
    import darwin.dataset  # noqa
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/dataset/__init__.py", line 1, in <module>
    from darwin.dataset.local_dataset import LocalDataset  # noqa
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/dataset/local_dataset.py", line 9, in <module>
    from darwin.dataset.utils import get_classes, get_release_path, load_pil_image
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/dataset/utils.py", line 16, in <module>
    from darwin.importer.formats.darwin import parse_path
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/importer/__init__.py", line 5, in <module>
    from .importer import import_annotations  # noqa
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/darwin/importer/importer.py", line 26, in <module>
    from mpire import WorkerPool, tqdm
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/mpire/__init__.py", line 4, in <module>
    from mpire.pool import WorkerPool
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/mpire/pool.py", line 21, in <module>
    from mpire.dashboard.connection_utils import get_dashboard_connection_details
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/mpire/dashboard/__init__.py", line 2, in <module>
    from mpire.dashboard.dashboard import connect_to_dashboard, start_dashboard
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/mpire/dashboard/dashboard.py", line 8, in <module>
    from pkg_resources import resource_string
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 803, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/phil/anaconda3/envs/darwin/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2762, in requires
    raise UnknownExtra(
pkg_resources.UnknownExtra: types-requests 2.28.11.15 has no such extra feature 'dev'
```

The only workaround I've found is not to include `darwin-py` as explicit dependency at all.

**Comment by owencjones** [comment] 2023-04-24 17:32
Hi,

Thanks for this, I'll raise a ticket in our internal system and aim to get a fix for this sorted in a future release.

Thanks for you help with raising issues.

Owen

**Comment by MkhIr** [comment] 2023-04-25 13:17
Hey Owen, 

Is this just raised or already addressed? Issue was reported on early march and I assume there is a big population who don't use poetry

**Comment by owencjones** [comment] 2023-08-21 11:33
This bug should be no longer present - the `pyproject.toml` no longer specifies the no existent dep.  I'll close for now, but if anyone recreates, feel free to reopen.

Thanks all.

Owen V7

**Closed by owencjones** 2023-08-21 11:33 UTC
